name: Run pre-commit hooks and pytest

on:
  push:
    branches:
      - main
    workflow-dispatch:
    pull_request:

jobs:
  pre-commit-checks:
    name: Pre-Commit Checks and Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7.2.1

      - name: run pre-commit checks
        run: uv run pre-commit run --all --color=always --show-diff-on-failure

      - name: run pytest
        run: uv run pytest
